CREATE DATABASE GROUP_5A;
USE GROUP_5A;

CREATE TABLE LOGIN
(
    USERNAME VARCHAR(15) NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL
);
SELECT * FROM LOGIN;
CREATE TABLE SIGN_IN
(
    FIRST_NAME VARCHAR(15) NOT NULL,
    LAST_NAME VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    MOBILE_NUMBER VARCHAR(15) NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL
);
SELECT * FROM SIGN_IN;

ALTER TABLE LOGIN CHANGE USERNAME EMAIL VARCHAR(15) NOT NULL;
ALTER TABLE LOGIN ADD PRIMARY KEY(EMAIL);
ALTER TABLE SIGN_IN ADD PRIMARY KEY(EMAIL);
ALTER TABLE SIGN_IN ADD USERNAME VARCHAR(15) UNIQUE NOT NULL, ADD CREATED_AT DATETIME NOT NULL;


CREATE TABLE REPORT
(
    EMAIL VARCHAR(50) PRIMARY KEY NOT NULL,
    PHONE_NO VARCHAR(15) UNIQUE NOT NULL,
    ON_DATE DATE NOT NULL,
    CATEOGARY VARCHAR(15) NOT NULL,
    PLACE VARCHAR(100),
    PICTURE VARCHAR(300) NOT NULL
);
SELECT * FROM REPORT;